#!/bin/bash

# install script on a new system inside of dev container

# export XDG_CONFIG_HOME="$HOME"/.config
#creating directories for bash prompt

#install  Nix packages form config.nix
nix-env -iA nixpkgs.myPackages

# apply dot files with chezmoi
chezmoi apply --source "$PWD"
